name: 'My Job will help to Planning for display Message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: macOs-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Execute Commands
        run: |
          date
          pwd
          ls
      - name: Version 12
        run: echo V12
      - name: Version 13
        run: echo V13
